### ISSUE TITLE
Problem with multiple annotations in a single line

### ISSUE THREAD

**Issue by JokerQyou** [SublimeLinter/SublimeLinter-annotations#10]
If multiple annotations are in the same line, only the first will be highlighted, all others are ignored.

``` python
def test():
    # TODO FIXME implement this test
    pass
```

In the above example, only the `TODO` keyword will be highlighted.

**Comment by braver** [comment]
Yes we stop scanning the line after the first match. What is the intention behind having both TODO and FIXME here?

**Comment by JokerQyou** [comment]
Well, this issue was created by me back in 2015, so I guess it was an outdated code style of mine at that time. You can actually reproduce with this example:

```python
def test():
    a=1,2  # TODO format this
    pass
```
