### ISSUE TITLE
Add screenshot of plugin in action in readme

### ISSUE THREAD

**Issue by matkoniecz** [SublimeLinter/SublimeLinter-annotations#11]
It not only makes readme more attractive (at least to me) but also shows what should be expected after installation.

I (probably) have some minor installation problem and one of things that I suspect is that by default changes are subtle or appear in some unexpected place. With screenshoot in readme I would be able to discard this possibility immediately.

**Comment by Kristinita** [comment]
+1

**Comment by braver** [comment]
Big UI changes are coming, so this isn't feasible right now. When things stabilise we might add them to the main SL repo.
