### ISSUE TITLE
Can I highlight code constructs that outside of the comment?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [SublimeLinter/SublimeLinter-annotations#12]
I not found about this in docs, at readme at GitHub I see that plugin only for comments.

For example, I want to highlight `console.log`

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/SublimeLinter-annotations#settings

Add `console.log` to errors or warning setting

**Comment by vitaly-zdanevich** [comment]
Yes I tried this but after saving I see highlight of added word only at commented lines

**Comment by EyMaddis** [comment]
LaTEX for example has `\todo{I have to do something}` which would be a fitting use for this feature

**Comment by geniusupgrader** [comment]
An Option in the settings for choosing the selector (comments, text, code) would be nice

**Comment by geniusupgrader** [comment]
I've tried to find a solution with the users `sublimelinter.sublime-settings` file, but I didn't find a good way to get the settings from there to set the selectors inside `linter.py`. So, for now just edit them manually in the `linter.py` file:
```python
    selectors = {
        '*': 'comment', '*': 'text'
    }
```
Or remove the line with selectors entirely.

**Comment by tobiasdiez** [comment]
Are there any updates on this issue? The workaround by @geniusupgrader doesn't work for me (probably, I make some mistakes while updating the linter.py file in `SublimeLinter-annotations.sublime-package`).

**Comment by braver** [comment]
Currently, unless someone wants to come forward and do something about this, it's not very high on the priority list for the currently active maintainers in this group.

**Comment by geniusupgrader** [comment]
@tobiasdiez have you tried to comment out the section from [my comment](https://github.com/SublimeLinter/SublimeLinter-annotations/issues/12#issuecomment-325114145)?
It should work

**Comment by braver** [comment]
You know, now that I read it again I understand that you want this plugin to highlight any kind of word anywhere in the code. That's not the right use case for this plugin. If you want to highlight console.log, eslint has a configuration for that. This plugin is aimed at highlighting markers in comments. You can fork it if you want it to do something else, but I'd like it to have a little focus.

**Comment by geniusupgrader** [comment]
@braver I can understand that you want to keep it simple and focused, but you suggesting a javascript linter, instead of nourishing this plugin? What about adding a option for this functionality?

**Comment by braver** [comment]
> a javascript linter

Definitely sounds like a JavaScript use case here right? I understand your wishes, but configurability always comes at a price of maintainability. We’re not doing excellently in that area. But it’s open source, I’m not stopping you from doing something.
