### ISSUE TITLE
mark_style randomly applied

### ISSUE THREAD

**Issue by LeonardoGentile** [SublimeLinter/SublimeLinter-annotations#13]
Hello,
I've noticed that the same type of annotation (for example FIXME) sometimes has the mark_style as selected in preferences and sometimes not.

For example these two screenshots belong to the same file. The first occurrence of  FIXME is not underlined (but the linter recognizes it because the gutter is red) and the second is correctly underlined. 

![slip_js_ _edhec](https://cloud.githubusercontent.com/assets/412061/16444621/394448da-3ddf-11e6-82a4-1e039f3b48f1.png)
![slip_js_ _edhec](https://cloud.githubusercontent.com/assets/412061/16444667/79eed832-3ddf-11e6-992d-8b58c07e983b.png)

**Comment by braver** [comment]
I cannot reproduce this using recent versions of this plugin and SL4.
