### ISSUE TITLE
Not working anymore (latest SublimeLinter and SublimeText3dev)

### ISSUE THREAD

**Issue by byaka** [SublimeLinter/SublimeLinter-annotations#21]
If i not missed - it worked for me prev week. But no jsut shows `annotations(ok)` in statusbar and dont highlight anything. I also have flake8 linter, it work no problems.

**Comment by braver** [comment]
Also works for me on ST dev builds. You need to debug your setup further because it doesn't seem to be on our end.

**Comment by byaka** [comment]
maybe u have any ideas can i can find problem?
my config
```json
      "annotations": {
          "disable": false,
          "args": [],
          "errors": [
              "#! ",
              "\\! "
          ],
          "excludes": [],
          "warnings": [
              "#~ ",
              "#? ",
              "\\? ",
              "\\~ "
          ]
      }
```
nothing changed last year. And no errors in console

**Comment by kaste** [comment]
Tried your settings

![image](https://user-images.githubusercontent.com/8558/39592833-47667b5e-4f08-11e8-86aa-7f5c13c806ef.png)

👌

**Comment by byaka** [comment]
ok so its problem on my side...
i'll check it with debug=true, maybe it shows any interesting

**Comment by byaka** [comment]
Tested with debug=true, tothing special..

```
SublimeLinter: log_handler.py:74: Logging installed; log level INFO
SublimeLinter: sublime_linter.py:43: debug mode: on
SublimeLinter: sublime_linter.py:44: version: 4.4.1
SublimeLinter: sublime_linter.py:241: Delay buffer 25 for 0.9s
SublimeLinter: sublime_linter.py:241: Delay buffer 25 for 0.9s
SublimeLinter: sublime_linter.py:364: detected syntax: python
SublimeLinter: #1 linter.py:737: 'annotations' is linting 'test.py'
SublimeLinter: sublime_linter.py:287: Linting buffer 25 took 0.27s

```
[linter.zip](https://github.com/SublimeLinter/SublimeLinter-annotations/files/1975730/linter.zip)
here this test file and my settings

**Comment by kaste** [comment]
Okay, now I understand. Look at my pic. I'm in a block comment and write e.g. `#?`. To match here for line comments you would start the comment via `#` and then your token follows. E.g. `# #! Here I am` matches. That means this plugin only parses the content of the comment if you will, the actual comment 'marker' is not part of it.

**Comment by byaka** [comment]
oh, thank u mate! Dont know why this worked for me early. Now it work correctly, awesome!
