### ISSUE TITLE
Would it be possible to add additional `info` scope?

### ISSUE THREAD

**Issue by tukusejssirs** [SublimeLinter/SublimeLinter-annotations#28]
IMHO, `NOTE` is not a warning, just a mere info message. Would it be possible to add `info` scope in addition to `warning` and `error`?

**Comment by kaste** [comment]
Sounds reasonable, but if you want it to happen, I suggest making a PR as it's unlikely someone else will take it.

**Comment by tukusejssirs** [comment]
Okay, I try and do that. :smiley:

---

Does `SublimeLinter.lint` have defined `INFO`? So that I could use the following `import`?

```python
from SublimeLinter.lint import Linter, ERROR, WARNING, INFO
```

As far as I understand it right, [it does not[(https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/linter.py). If that is the case, how do you think I should solve this issue?

**Comment by kaste** [comment]
There is no need to use these as they translate to simple strings.  `ERROR` really is `"error"`.

**Comment by tukusejssirs** [comment]
Thanks! :smiley:

I tried to implement this issue, but for some reason it does not work as I’d expect; see below.

```python
# Text in code
# NOTE: info

# Current output
6:3    error    annotations        info

# Desired output
6:3    info     annotations:NOTE   info
```

Even if I remove [`word = match.group('info')`](https://github.com/tukusejssirs/SublimeLinter-annotations/blob/add_info_scope/linter.py#L86), the output is the same.

Could you look at the code please? :smiley:

**Comment by kaste** [comment]
It's the first regex starting on L40.  We actually don't capture or expect the group `note` here.  On newer SublimeLinter versions we accept any error type, and the regex line should be something like 

```
    regex = (
        r'^(?P<line>\d+):(?P<col>\d+):'
        r' (?P<error_type>.+) \((?P<code>.+)\):'
        r' (?P<message>.*)'
    )
```

(No need to compile the regex because SublimeLinter will do this on load.)

**Comment by kaste** [comment]
Maybe the lazy ones `.+?` instead of `.+`.

**Comment by tukusejssirs** [comment]
Perfect! Thanks!

I’ve got to questions:
1. Could I add `ERROR`, `WARNING` and `INFO` words to the `defaults` object? Of course, I’d upthe `README.md`.
2. Is `"warnings": "[FOO], BAR",` syntax from `README.md` correct? It does not work for me (actually, it makes the plugin unworkable (it does not match any word).

**Comment by kaste** [comment]
1. Just like you did already, yes.

```
    defaults = {
        'selector': '',  # select all views
        'errors': ['FIXME'],
        'warnings': ['TODO', '@todo', 'XXX', 'WIP'],
        'infos': ['NOTE', 'README'],
    }
```
2. No `"[FOO], BAR"` is a typo, must be an array

**Comment by tukusejssirs** [comment]
>     1. Just like you did already, yes.
> 
> 
> ```
>     defaults = {
>         'selector': '',  # select all views
>         'errors': ['FIXME'],
>         'warnings': ['TODO', '@todo', 'XXX', 'WIP'],
>         'infos': ['NOTE', 'README'],
>     }
> ```

I know _how_ to accomplish this, however, my question is whether I could _add_ them into the `defaults` object. :wink:

>     1. No `"[FOO], BAR"` is a typo, must be an array

I’ll fix this unless you are against it.

**Comment by kaste** [comment]
1. Yes and 2. fix it

**Comment by kaste** [comment]
Oh, I now see that "info" is a bit strangely named, for other linters we have the more common "note" type.  So you can basically say, here "that's an error", or "this is a note", but you rarely say "that's an info".  Had you something special in mind with the "infos", or can we rename it?

**Comment by tukusejssirs** [comment]
> Had you something special in mind with the "infos", or can we rename it?

You can rename it if you think it is better. However, IMHO it is better be named `info`, because IMHO `NOTE`s and `README`s are used to provide additional information someone who reads the code might overlook or to explain a hard-to-understand portion of code. In look at the scopes as if they were logs e.g. in Javascript and these three are IMHO the three basic log types.

On the other hand, a `note` and `info` scopes are more or less the same, therefore from my point of view (and how I use this scope) it does not really matter.

---

A bit OT: how could we colour the border of the `info`/`note` scope word using a different colour? Currently `error`s are red, `warning`s are yellow and `info`s are red. Could we use e.g. light blue for `info`s? Where could I change this?

**Comment by kaste** [comment]
Just released it as is.  🚀 

Styles go into the settings file.  For example:

```
        "annotations": {
            "styles": [
                {
	 				"types": ["info"],
                    "scope": "markup",
                    "mark_style": "stippled_underline",
                    "icon": "pointer",
                    "priority": 1,
                }
            ]
        },
```

to limit this style to this linter.  Or one level up in the "styles" section.

**Comment by tukusejssirs** [comment]
Thanks for the inro, as well as the new release! 🙏

**Comment by tukusejssirs** [comment]
> Just released it as is. rocket
> 
> Styles go into the settings file. For example:
> 
> ```
>         "annotations": {
>             "styles": [
>                 {
> 	 				"types": ["info"],
>                     "scope": "markup",
>                     "mark_style": "stippled_underline",
>                     "icon": "pointer",
>                     "priority": 1,
>                 }
>             ]
>         },
> ```
> 
> to limit this style to this linter. Or one level up in the "styles" section.

@kaste, just tried to play with this and immediately after saving the settings file, the ST3 log shows with the following error:

```python
Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
'linters' > 'annotations' > 'styles' > 'types': 'info' is not one of ['error', 'warning']
```

That said, it works as expected.

---

Anyway, where can I get the list of valid values of `scope`, `mark_style` and `icon`? I’ve searched through SL docs and found only [this page](http://www.sublimelinter.com/en/stable/linter_settings.html?highlight=icon#styles) with two examples.

**Comment by kaste** [comment]
If you edit the settings, you should have a split screen, on the left the default settings.  We have comments in there.

**Comment by tukusejssirs** [comment]
> If you edit the settings, you should have a split screen, on the left the default settings. We have comments in there.

I think you misunderstood my comment. I know how to edit the package settings in ST3 and I already done what you said (I also said it works as expected).

The issue I talk about is the log; see the screenshot below. This error shows up each time I save the SL settings.

```python
Unable to open /home/ts/.config/sublime-text-3/Packages/SublimeLinter/SublimeLinter.sublime-settings
reloading settings Packages/User/SublimeLinter.sublime-settings
SublimeLinter: WARNING: Invalid settings in 'Packages/User/SublimeLinter.sublime-settings'
```

![st3_sl_annotations](https://user-images.githubusercontent.com/5111894/107130151-b6844d00-68c2-11eb-9649-d98140b073bb.png)

As I said, it works, but to suppress this error, it might be required to make some modifications in SL.

Also note that upon saving the SL settings, in the ST3 console the following error shows up (it does not happen when I comment out the the first element in `styles[]` array, which is dealing with the `info` scope of SL-Annotations):

**Comment by kaste** [comment]
Docs are open source just as the code.  

The validation thing is of course a bug, a simple one in the validation schema file.
