### ISSUE TITLE
Handle `TODO(...)`, `NOTE(...)`?

### ISSUE THREAD

**Issue by woodruffw** [SublimeLinter/SublimeLinter-annotations#33]
First of all, thanks for this plugin!

A common style for `TODO`, `NOTE`, etc.-style comments is to include the author's initials or an issue tracker number in parenthesis, like so:

```
// TODO(#XXX): Requires changes to FooWidget.
// NOTE(ww): Keep these components in sync with BarWidget.
```

Currently, the plugin renders these a little funkily:

<img width="953" alt="Screen Shot 2021-11-03 at 8 42 23 PM" src="https://user-images.githubusercontent.com/3059210/140238383-ac0ce505-abe0-4cc6-a51f-61110ac4249e.png">

Is there any interest in supporting these? If so, it should be a relatively small regular expression change, one that I'm happy to contribute.

**Comment by cixtor** [comment]
This type of marked comments are also common in Go, so much that the `go doc` command has specific instructions to parse any note with a marker of 2 or more upper case [A-Z] letters and a UID of at least one character, as you can see here: [golang/go:/src/go/doc/doc.go](https://github.com/golang/go/blob/61d789db3a52e4570596f1fd15122358deb73b77/src/go/doc/doc.go#L85-L93) and the corresponding tests in [golang/go:/src/go/doc/testdata/a0.go](https://github.com/golang/go/blob/61d789db3a52e4570596f1fd15122358deb73b77/src/go/doc/testdata/a0.go#L8-L40).

I would love to see marked comments support in SublimeLinter-annotations. What do you think, @kaste ?

**Comment by kaste** [comment]
Sure would be great.  Can you put the authors signature in the message, or do you want to capture this, e.g. `NOTE(kaste)`, as `code`?

**Comment by woodruffw** [comment]
Awesome! I'll try to set aside some time this week to implement it then.

> Can you put the authors signature in the message, or do you want to capture this, e.g. `NOTE(kaste)`, as `code`?

IMO it makes sense to include it in the message. I actually think the current message format is perfect; just a tweak to the regexp to capture the entire `WORD(body)` is all I think it needs :slightly_smiling_face:
