### ISSUE TITLE
Empty array for settings entry disables all other annotations

### ISSUE THREAD

**Issue by stinos** [SublimeLinter/SublimeLinter-annotations#39]
For instance with
```
"annotations": {
  "infos": [],
},
```
in the sublime-settings file, things like `TODO` etc do not get annotated anymore.

Reason is likely that the result of `mark_regex_template.format_map(options)` in linter.py with becomes

```
(?:(?P<info>)|(?P<warning>\bTODO\b|\@todo\b|\bXXX\b|\bWIP\b|\bWARNING\b)|(?P<error>\bFIXME\b|\bERROR\b)):?\s*(?P<message>.*)
```

which because of the missing text in the `info` capture group matches everything. I'd expect SublimeLinter to then mark all lines, but it doesn't do that, not sure why, maybe because the output format of `Annotations.run()` doesn't match what it expects because the match group will be empty?

Strangely enough lines like

```
# Foo (bar): baz
```

do get annotated though. Some easter egg on the `):` sad smiley? 

Trying to work around this I just entered `"infos": [""]` but that results in

```
  File "Installed Packages\SublimeLinter-annotations.sublime-package\linter.py", line 61, in run
    options[option] = '|'.join(_escape_words(words))
  File "Installed Packages\SublimeLinter-annotations.sublime-package\linter.py", line 26, in _escape_words
    if value[0].isalnum() or value[0] == '_':
```

so need to effectively enter something there to get it working like `"infos": ["ShouldNotMatchAnything"]`

**Comment by kaste** [comment]
Yes, that's a bug.  (And sorry for taking so long to respond.)

**Comment by kaste** [comment]
> which because of the missing text in the info capture group matches everything

It *always* matches but always the empty string from my understanding.

**Comment by stinos** [comment]
Thanks, can confirm this is fixed
