### ISSUE TITLE
Annotation style only captures 'errors' type

### ISSUE THREAD

**Issue by Flexnm** [SublimeLinter/SublimeLinter-annotations#42]
Hello, It seems that since the last update the annotations no longer capture correctly. The only `style` from the `styles` array that is being captured is one that is labeled in the `types` as `["errors"]` (previously worked with using singular of the infos/errors/warnings types).
I tried changing order of the arrays members but it seems that only the literal keyword "errors" is captured.
This means that to all the annotations are getting that style applied to them (they are all treated as "errors" type regardless of the annotation being set (i have `"infos": ["INFO"]` that is set to be yellow but it being applied the red of the `"errors"` type)

**Comment by kaste** [comment]
Yep, a regression.  💩  Thanks for opening the issue.

(That's why I hate that we don't have unit tests here; you just can't make a random change on a weekend without staring at the code for hours *or* you introduce a stupid bug.)
