### ISSUE TITLE
need an option for annotations style

### ISSUE THREAD

**Issue by mayuroks** [SublimeLinter/SublimeLinter-annotations#7]
Currently the annotations are only outlined. Its kinda makes them hard to spot. There should be an option called

``` ruby
annotations_style: filled # (available styles are outline, filled, underline, highlight_entire_line)
```

Similar feature is available for code block highlighting in BracketsHighlighter.

**Comment by lionel-bijaoui** [comment]
Yes and they shouldn't be classified as error in the bottom bar
```Error: TODO my todo``` should be ```TODO: my todo```

**Comment by braver** [comment]
This isn't something that can be done at the linter plugin level. In Sublime Linter 4 there will be an option to specify highlight styles per linter.

**Comment by KushMastaFresh** [comment]
Any chance this feature has been added yet? I'm on Sublime Text 3.1.1 and am trying to switch the mark style to fill, but it seems to be locked to outline still

**Comment by kaste** [comment]
This has been resolved with SublimeLinter 4. Maybe share your config and a screenshot.

**Comment by KushMastaFresh** [comment]
Thanks for the reply (and a very speedy reply too), it's much appreciated

Here are my SublimeLinter settings. It's gotta be something I'm doing wrong then if it's been resolved, anyway, here's the screencap

<img width="360" alt="sublimelinter settings" src="https://user-images.githubusercontent.com/13029619/42416219-7dbbc162-821d-11e8-85da-d00a276ee88a.png">

**Comment by kaste** [comment]
Ah, look here http://www.sublimelinter.com/en/stable/linter_settings.html#styles
