### ISSUE TITLE
TODO categorized as Error

### ISSUE THREAD

**Issue by adam-beck** [SublimeLinter/SublimeLinter-annotations#8]
This is the `linters` property I have in my user settings:

``` json
"linters": {
            "annotations": {
                "@disable": false,
                "args": [],
                "errors": [
                    "FIXME"
                ],
                "excludes": [],
                "warnings": [
                    "TODO",
                    "README"
                ]
            }
        },
```

Yet, SublimeLinter is still categorizing this as an Error. When I list all errors it appears there and it also appears in the status bar as 1 Error whenever I have a `TODO` statement.

**Comment by JokerQyou** [comment]
I found something similar to this: if I move `FIXME` from `errors` to `warnings`, this keyword will not be highlighted. In other words, the `FIXME` note will only be highlighted if we treat it as error. This is really strange behavior.

**Comment by braver** [comment]
I cannot reproduce this using recent versions of this plugin and SL4.
